version: 2
jobs:
  build_deploy_master:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
            - v1-dependencies-
      - run:
          name: npm install
          command: npm i && cd functions && npm i
      - save_cache:
          paths:
            - node_modules
            - functions/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
      - run:
          name: build Client and Functions
          command: npm run build
      - run:
          name: deploy to Firebase Hosting and Functions
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build_deploy_master:
    jobs:
      - build_deploy_master:
          filters:
            branches:
              only: master