version: 2.1
jobs:
  deploy_app:
    working_directory: ~/sample
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run:
          name: envの追加
          command: |
            echo DEBUG=${ENV} > ~/.env
            echo REACT_APP_API_KEY=${REACT_APP_API_KEY} >> ~/.env
            echo REACT_APP_AUTH_DOMAIN=${REACT_APP_AUTH_DOMAIN} >> ~/.env
            echo REACT_APP_PROJECT_ID=${REACT_APP_PROJECT_ID} >> ~/.env
            echo REACT_APP_STORAGE_BUCKET=${REACT_APP_STORAGE_BUCKET} >> ~/.env
            echo REACT_APP_MESSAGING_SENDER_ID=${REACT_APP_MESSAGING_SENDER_ID} >> ~/.env
            echo REACT_APP_APP_ID=${REACT_APP_APP_ID} >> ~/.env
            echo REACT_APP_STRIPE_API_KEY=${REACT_APP_STRIPE_API_KEY} >> ~/.env
            ls -al
      - run:
          name: node_modulesのインストール
          command: |
            npm i && cd functions && npm i
            ls -al
      - run:
          name: ビルド
          command: |
            npm run build
            ls -al
            cd functions && npm run build
            ls -al
      - run:
          name: buildフォルダの確認
          command: ls -la build
      - run:
          name: firebase-toolsのインストール
          command: |
            npm install --dev firebase-tools
      - run:
          name: firebaseへデプロイ
          command: |
            ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
  version: 2.1
  build-deploy:
    jobs:
      - deploy_app:
          filters:
            branches:
              only: master
