import { firebase } from "../firebase/config";
import { Furniture } from "../types/dashboard";
import theme_1 from "../assets/image/furniture_1.jpg";
import furniture_bed from "../assets/image/furniture_bed.jpg";
import furniture_blanket from "../assets/image/furniture_blanket.jpg";
import furniture_chair from "../assets/image/furniture_chair.jpg";
import furniture_lamp from "../assets/image/furniture_lamp.jpg";
import furniture_plant from "../assets/image/furniture_plant.jpg";
import furniture_rug from "../assets/image/furniture_rug.jpg";
import furniture_shelf from "../assets/image/furniture_shelf.jpg";
import furniture_sofa from "../assets/image/furniture_sofa.jpg";

export const recommendation: Furniture = {
  width: 97,
  depth: 180,
  height: 50,
  price: 39900,
  baseColor: "white",
  subColor: "grey",
  stock: 4,
  likedCount: 23,
  category: "bed",
  name: "ベッド",
  imageUrl: theme_1,
  details:
    "ドライフラワーと照明が特徴的なワンルームの一人暮らしインテリア。テキトタイルはグレー系で揃えられ、IKEAの毛布やサイドテーブル、照明などで特徴立たせている、シンプルな雰囲気のお部屋。",
  createdAt: firebase.firestore.Timestamp.fromDate(new Date()),
};

export const db: Array<Furniture> = [
  {
    width: 97,
    depth: 180,
    height: 50,
    price: 39900,
    baseColor: "white",
    subColor: "grey",
    stock: 4,
    likedCount: 23,
    category: "bed",
    name: "ベッド",
    imageUrl: furniture_bed,
    details: "texttexttexttexttexttexttexttexttexttext",
    createdAt: firebase.firestore.Timestamp.fromDate(new Date()),
  },
  {
    width: 40,
    depth: 40,
    height: 60,
    price: 4999,
    baseColor: "white",
    subColor: "grey",
    stock: 19,
    likedCount: 2,
    category: "table",
    name: "テーブル",
    imageUrl: furniture_chair,
    details: "texttexttexttexttexttexttexttexttexttext",
    createdAt: firebase.firestore.Timestamp.fromDate(new Date()),
  },
  {
    width: 95,
    depth: 64,
    height: 68,
    price: 10990,
    baseColor: "white",
    subColor: "grey",
    stock: 6,
    likedCount: 33,
    category: "sofa",
    name: "ソファ",
    imageUrl: furniture_sofa,
    details: "texttexttexttexttexttexttexttexttexttext",
    createdAt: firebase.firestore.Timestamp.fromDate(new Date()),
  },
  {
    width: 132,
    depth: 0,
    height: 38,
    price: 20280,
    baseColor: "white",
    subColor: "grey",
    stock: 3,
    likedCount: 1,
    category: "light",
    name: "間接照明",
    imageUrl: furniture_lamp,
    details: "texttexttexttexttexttexttexttexttexttext",
    createdAt: firebase.firestore.Timestamp.fromDate(new Date()),
  },
  {
    width: 130,
    depth: 190,
    height: 0,
    price: 4620,
    baseColor: "white",
    subColor: "grey",
    stock: 4,
    likedCount: 12,
    category: "carpet",
    name: "ラグ",
    imageUrl: furniture_rug,
    details: "texttexttexttexttexttexttexttexttexttext",
    createdAt: firebase.firestore.Timestamp.fromDate(new Date()),
  },
  {
    width: 85,
    depth: 55,
    height: 0,
    price: 4999,
    baseColor: "white",
    subColor: "grey",
    stock: 4,
    likedCount: 12,
    category: "bed",
    name: "毛布",
    imageUrl: furniture_blanket,
    details: "texttexttexttexttexttexttexttexttexttext",
    createdAt: firebase.firestore.Timestamp.fromDate(new Date()),
  },
  {
    width: 70,
    depth: 25,
    height: 70,
    price: 7000,
    baseColor: "white",
    subColor: "grey",
    stock: 432,
    likedCount: 123,
    category: "shelf",
    name: "ラック",
    imageUrl: furniture_shelf,
    details: "texttexttexttexttexttexttexttexttexttext",
    createdAt: firebase.firestore.Timestamp.fromDate(new Date()),
  },
  {
    width: 55,
    depth: 60,
    height: 150,
    price: 15176,
    baseColor: "white",
    subColor: "grey",
    stock: 9,
    likedCount: 81,
    category: "plant",
    name: "観葉植物",
    imageUrl: furniture_plant,
    details: "texttexttexttexttexttexttexttexttexttext",
    createdAt: firebase.firestore.Timestamp.fromDate(new Date()),
  },
];
